#ifndef CONFIG_H
#define CONFIG_H

#define SENSING_PERIOD_SECONDS 60
#define MEAN_HUMIDITY 41.1
#define STD_HUMIDITY 5.83
#define MAX_STEP 2.00
#define BUFFER_SIZE 60

#define CLOUD_SERVER_EP "coap://[fd00::1]:5683"
#define REGISTRATION_RESOURCE_PATH "register"
#define REGISTRATION_ACK_CODE CONTENT_2_05
#define MAX_REGISTRATION_RETRY 3
#define REGISTRATION_WAIT_SECONDS 5

#endif // CONFIG_H