#ifndef CONFIG_H
#define CONFIG_H

#define CLOUD_SERVER_EP "coap://[fd00::1]:5683"
#define REGISTRATION_RESOURCE_PATH "register"
#define REGISTRATION_ACK_CODE CONTENT_2_05
#define REGISTRATION_WAIT_SECONDS 5
#define MAX_REGISTRATION_RETRY 5
#define SENSOR_SAMPLE_INTERVAL 10

#endif
