#ifndef CONFIG_H
#define CONFIG_H

#define CLOUD_SERVER_EP "coap://[fd00::202:2:2:2]:5683"
#define REGISTRATION_RESOURCE_PATH "registration"
#define REGISTRATION_ACK_CODE CREATED_2_01
#define REGISTRATION_WAIT_SECONDS 5
#define MAX_REGISTRATION_RETRY 5
#define SENSOR_SAMPLE_INTERVAL 10

#endif
