CONTIKI_PROJECT = light-sensor
PROJECT_SOURCEFILES += \
  res-light.c \
  button-handler.c \
  monitoring-process.c \
  coap-client-post.c \
  sensor-simulation.c

all: $(CONTIKI_PROJECT)

CONTIKI = ../contiki-ng
include $(CONTIKI)/Makefile.include
