#ifndef CONFIG_H
#define CONFIG_H

#define SENSING_PERIOD_SECONDS 60
#define MEAN_TEMPERATURE 26.34
#define STD_TEMPERATURE 1.85
#define MAX_STEP 0.50
#define BUFFER_SIZE 60

#define CLOUD_SERVER_EP "coap://[fd00::202:2:2:2]:5683"
#define REGISTRATION_RESOURCE_PATH "registration"
#define REGISTRATION_ACK_CODE CREATED_2_01
#define MAX_REGISTRATION_RETRY 3
#define REGISTRATION_WAIT_SECONDS 5

#endif // CONFIG_H